MyEvernote.WebApp/Controllers/EvernoteUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyEvernote.Business;
using MyEvernote.Business.Result;
using MyEvernote.Entities;

namespace MyEvernote.WebApp.Controllers
{
    public class EvernoteUserController : Controller
    {
        private EvernoteUserManager evernoteUserManager = new EvernoteUserManager();

        // GET: EvernoteUser
        public ActionResult Index()
        {
            return View(evernoteUserManager.List());
        }

        // GET: EvernoteUser/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvernoteUser evernoteUser = evernoteUserManager.Find(x=> x.Id==id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }

        // GET: EvernoteUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EvernoteUser/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EvernoteUser evernoteUser)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");

            if (ModelState.IsValid)
            {
                BusinessLayerResult<EvernoteUser> res = evernoteUserManager.Insert(evernoteUser);

                if (res.Errors.Count>0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(evernoteUser);
                }
                return RedirectToAction("Index");
            }

            return View(evernoteUser);
        }

        // GET: EvernoteUser/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvernoteUser evernoteUser = evernoteUserManager.Find(x=> x.Id==id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }

        // POST: EvernoteUser/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EvernoteUser evernoteUser)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");

            if (ModelState.IsValid)
            {
                BusinessLayerResult<EvernoteUser> res = evernoteUserManager.Update(evernoteUser);

                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                }
                return RedirectToAction("Index");
            }
            return View(evernoteUser);
        }

        // GET: EvernoteUser/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvernoteUser evernoteUser = evernoteUserManager.Find(x=> x.Id==id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }

        // POST: EvernoteUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EvernoteUser evernoteUser = evernoteUserManager.Find(x => x.Id == id);
            evernoteUserManager.Delete(evernoteUser);
            return RedirectToAction("Index");
        }

    }
}

MyEvernote.WebApp/Views/EvernoteUser/Create.cshtml
@model MyEvernote.Entities.EvernoteUser
@using MyEvernote.WebApp

@{
    ViewBag.Title = "Create";
}

<link href="~/Content/validation-summary.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <h2>Create</h2>
        <h4>EvernoteUser</h4>
        <hr />
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(false)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAdmin)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span> Create </button>
                @Html.ActionLink("Back to List", "Index", "EvernoteUser", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

MyEvernote.WebApp/Views/EvernoteUser/Delete.cshtml
@model MyEvernote.Entities.EvernoteUser

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Delete</h2>
        <h3>Are you sure you want to delete this?</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>EvernoteUser</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Surname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Surname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProfileImageFilename)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProfileImageFilename)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ActivateGuid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ActivateGuid)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsAdmin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedUsername)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedUsername)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash"></span> Delete
                </button>
                @Html.ActionLink("Back to List", "Index", "EvernoteUser", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

MyEvernote.WebApp/Views/EvernoteUser/Details.cshtml
@model MyEvernote.Entities.EvernoteUser

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Details</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>EvernoteUser</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Surname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Surname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProfileImageFilename)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProfileImageFilename)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ActivateGuid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ActivateGuid)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsAdmin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedUsername)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedUsername)
            </dd>

        </dl>
    </div>

    <div class="col-md-8 col-md-offset-2">
        <p>
            <a href="/EvernoteUser/Edit/@Model.Id" class="btn btn-warning">
                <span class="glyphicon glyphicon-edit"></span> Edit
            </a>
            @Html.ActionLink("Back to List", "Index", "EvernoteUser", null, new { @class = "btn btn-default" })
        </p>
    </div>

</div>

MyEvernote.WebApp/Views/EvernoteUser/Edit.cshtml
@model MyEvernote.Entities.EvernoteUser

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <h2>Edit</h2>
        <h4>EvernoteUser</h4>
        <hr />
    </div>
</div>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(false)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAdmin)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <button type="submit" class="btn btn-success"> Save </button>
                @Html.ActionLink("Back to List", "Index", "EvernoteUser", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

MyEvernote.WebApp/Views/EvernoteUser/Index.cshtml
@using MyEvernote.WebApp
@model IEnumerable<MyEvernote.Entities.EvernoteUser>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Kullanıcılar</h2>
    </div>
</div>


<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <p>
            @Boostrap.LinkButton("/EvernoteUser/Create", "primary", "", "", "plus", "Create")
        </p>
        <table class="table table-hover">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsAdmin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedUsername)
                </th>
                <th> Seçenekler </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsAdmin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedUsername)
                    </td>
                    <td class="col-md-2">
                        @Boostrap.LinkButton("/EvernoteUser/Edit/" + item.Id, "warning", "btn-xs", "Edit", "edit", string.Empty)

                        @Boostrap.LinkButton("/EvernoteUser/Details/" + item.Id, "info", "btn-xs", "Details", "search", string.Empty)

                        @Boostrap.LinkButton("/EvernoteUser/Delete/" + item.Id, "danger", "btn-xs", "Delete", "trash", string.Empty)


                    </td>
                </tr>
            }

        </table>
    </div>
</div>